services:
  bttda-dev:
    image: localhost/bttda:${TENSORLY_BACKEND:-numpy}
    build:
      context: .
      dockerfile: Containerfile
      target: ${TENSORLY_BACKEND:-numpy}
    volumes:
      - ./src:/project/src:Z
      - ./tests:/project/tests:Z
      - ./notebooks:/project/notebooks:Z
      - $HOME/mne_data:/root/mne_data:Z
      - $HOME/.jupyter:/root/.jupyter:Z
      - $HOME/.ipython:/root/.ipython:Z
    ports:
      - "8888:8888"
    entrypoint: "jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token=abcd"
    security_opt:
      - "label=disable"
    devices:
      - "nvidia.com/gpu=all"
