name: bttda-cuda
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
    #- cupy cuda-version=12.6
  - pip
  - pandas
  - pip:
    - -e .[experiments]
  - dask
  - dask-jobqueue
variables:
  TENSORLY_BACKEND: "cupy"
  TENSORLY_TENALG_BACKEND: "einsum"
  CUPY_ACCELLERATORS: "cutensor,cub"
